language: cpp
dist: trusty
sudo: required

os:
- linux
compiler:
- g++

before_install:
- git clone --depth=1 https://github.com/nnarain/travis-ci-scripts.git ~/scripts
- cd ~/scripts/ && ./bootstrap && cd -
- preinstall_general

install:
- install_general
- chmod +x ./scripts/travis_deploy_docs
- sudo apt-get --allow-unauthenticated install -y doxygen graphviz

script:
- mkdir build && cd build
- cmake .. -DBUILD_EXAMPLE="OFF" -DBUILD_DOCS="ON" -DCMAKE_BUILD_TYPE=Release
- make && make check
- cd ..

after_success:
- "./scripts/travis_deploy_docs $TRAVIS_BRANCH $GITHUB_API_TOKEN"
- cd build
- make package
- export ARTIFACTS=$(ls -d1 $PWD/*.tar.gz)

deploy:
  provider: releases
  api_key:
    secure: tkje4Q6TX/nuFFvyEnpltnaonPlf17Mcjxg8+Lb8QjH+3bF4E1emGZ+TYyl1oHtW8ePAFQjudEUtYPdPJayLJ/5iNtofMS5s7OPTB3cuhAFBcseHaTxzaHcLDHDmDqyQGtq3kOc7fxV0qRtGHrPVSRXRM7GaswIfCLxNkrOGUNR0qfZ3vNLrEy78kgR9HaUwCrA9IC7Esbgv6FFy4PKO+fOv7mowgjfvBw3piaL1yDBPKioKKE6g/NZRXdjOQxhwFnB2Z5JRM+qVuJwbJd3QGCFX0AJMSNnf3j+dy6tPsi/gzmWUuibjqFC7mvOVv32nU1CixLRV8t+Eo7Nz37/5+fPIMzkQmSpSdvMyfigL9jYz8ue3ZFeTRTLyradJJTA7A8tUIFwR+j/0hJuW/ahxppj7Sade70jDq+gLkghbpELQRU4GE/+7E+AYeQ8dCIl7boJNASoGXXBnDogj8n1oKwEAhNttUJ+L2yR7u99j6KpQhYCBo9tW+C+piwYrULtG9/oWnwfQbAuzcUnJzHk6U19XQBI1hoOETHBn3/1Wzsaj3aldZEDU8sybUhzy9ZUt3Ux9v3GdaW+TGbblMHkhIJte9pJWS3iq5H6FUbnFw8nV61XoAYE574FcRD5ovn1/gi/AJuAWuTV5szHlFzRZEULdJXVmmayQ3nmdEU0yM/I=
  file: "${ARTIFACTS}"
  skip_cleanup: true
  on:
    tags: true
