language: cpp
dist: xenial
sudo: required

os:
- linux
compiler:
- g++
- clang

python:
  - "3.6"

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - deadsnakes
    packages:
      - cppcheck
      - lcov
      - python3.6

install:
- bash scripts/ci_install
- sudo apt-get --allow-unauthenticated install -y doxygen graphviz

script:
- mkdir build && cd build
- cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DWITH_COVERAGE=ON -DBUILD_DOCS=ON
- cd .. && cppcheck -q --enable=all --inconclusive --force --suppressions-list=./config/cppcheck-suppress.txt src/gameboycore/ && cd -
- make
- make check && make run_test_roms
- cd ..

after_success:
- bash ./scripts/travis_deploy_docs $TRAVIS_BRANCH $GITHUB_API_TOKEN
- cd build
- make package
- export ARTIFACTS=$(ls -d1 $PWD/*.tar.gz)

- ../scripts/coverage
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

deploy:
  provider: releases
  api_key:
    secure: tkje4Q6TX/nuFFvyEnpltnaonPlf17Mcjxg8+Lb8QjH+3bF4E1emGZ+TYyl1oHtW8ePAFQjudEUtYPdPJayLJ/5iNtofMS5s7OPTB3cuhAFBcseHaTxzaHcLDHDmDqyQGtq3kOc7fxV0qRtGHrPVSRXRM7GaswIfCLxNkrOGUNR0qfZ3vNLrEy78kgR9HaUwCrA9IC7Esbgv6FFy4PKO+fOv7mowgjfvBw3piaL1yDBPKioKKE6g/NZRXdjOQxhwFnB2Z5JRM+qVuJwbJd3QGCFX0AJMSNnf3j+dy6tPsi/gzmWUuibjqFC7mvOVv32nU1CixLRV8t+Eo7Nz37/5+fPIMzkQmSpSdvMyfigL9jYz8ue3ZFeTRTLyradJJTA7A8tUIFwR+j/0hJuW/ahxppj7Sade70jDq+gLkghbpELQRU4GE/+7E+AYeQ8dCIl7boJNASoGXXBnDogj8n1oKwEAhNttUJ+L2yR7u99j6KpQhYCBo9tW+C+piwYrULtG9/oWnwfQbAuzcUnJzHk6U19XQBI1hoOETHBn3/1Wzsaj3aldZEDU8sybUhzy9ZUt3Ux9v3GdaW+TGbblMHkhIJte9pJWS3iq5H6FUbnFw8nV61XoAYE574FcRD5ovn1/gi/AJuAWuTV5szHlFzRZEULdJXVmmayQ3nmdEU0yM/I=
  file: "${ARTIFACTS}"
  skip_cleanup: true
  on:
    tags: true
